# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merge.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmerge.proto\"m\n\x06\x43onfig\x12\x11\n\tdoc_order\x18\x01 \x03(\t\x12\"\n\x08rotation\x18\x02 \x03(\x0b\x32\x10.Config.Rotation\x1a,\n\x08Rotation\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\t\x12\x10\n\x08rotation\x18\x02 \x01(\x05\"P\n\x0fPDFMergeRequest\x12\x0f\n\x07\x64oc_ids\x18\x01 \x03(\t\x12\x13\n\x0bprocess_tag\x18\x02 \x01(\t\x12\x17\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x07.Config\"#\n\x10PDFMergeResponse\x12\x0f\n\x07\x64oc_ids\x18\x01 \x03(\t27\n\x05merge\x12.\n\x05Merge\x12\x10.PDFMergeRequest\x1a\x11.PDFMergeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'merge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONFIG']._serialized_start=15
  _globals['_CONFIG']._serialized_end=124
  _globals['_CONFIG_ROTATION']._serialized_start=80
  _globals['_CONFIG_ROTATION']._serialized_end=124
  _globals['_PDFMERGEREQUEST']._serialized_start=126
  _globals['_PDFMERGEREQUEST']._serialized_end=206
  _globals['_PDFMERGERESPONSE']._serialized_start=208
  _globals['_PDFMERGERESPONSE']._serialized_end=243
  _globals['_MERGE']._serialized_start=245
  _globals['_MERGE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
